version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: myapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"  # Mapping MySQL container port to host
    volumes:
      - mysql_data:/var/lib/mysql

flask:
    build:
      context: ./flask-app
    container_name: myapp_flask
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DATABASE=app_db
    command: flask run --host=0.0.0.0 --port=5009
    network_mode: "host"
    depends_on:
      - mysql
    ports:
      - "5009:5009"
    volumes:
      - ./flask-app:/app

volumes:
  mysql_data: